# Forecasting Agent Configuration

agent:
  id: "forecasting-agent"
  name: "Forecasting Agent"
  type: "PredictiveAnalyticsAgent"
  category: "sales-intelligence"
  version: "1.0.0"
  description: "Predictive analytics and pipeline intelligence for sales forecasting"
  
runtime:
  realtime: true
  maxInstances: 8
  memoryLimit: "2GB"
  cpuLimit: "1.5"
  
tools:
  - "claude-forecasting"
  - "statistical-modeling"
  - "pipeline-analytics"
  - "trend-analysis"
  - "risk-assessment"

triggers:
  - "deal.stage_changed"
  - "deal.value_updated"
  - "lead.converted"
  - "deal.closed_won"
  - "deal.closed_lost"
  - "forecast.requested"
  - "model.retrain_requested"
  - "pipeline.updated"

events_emitted:
  - "forecast.generated"
  - "forecast.alert"
  - "forecast.completed"
  - "forecast.failed"
  - "deal.probability_updated"
  - "models.retrained"
  - "risk.detected"
  - "opportunity.identified"

performance_requirements:
  response_time: "3s"
  throughput: "500/5min"
  memory_usage: "<2GB"
  cpu_usage: "<150%"
  concurrent_forecasts: 50

forecasting:
  predictionHorizon: 7776000000  # 90 days in milliseconds
  confidenceThreshold: 0.75
  modelRefreshInterval: 86400000  # 24 hours
  historicalDataRange: 31536000000  # 365 days
  enableRealTimePredictions: true
  
  prediction_models:
    primary_model: "ensemble"  # ensemble, linear_regression, random_forest, neural_network
    fallback_model: "linear_regression"
    model_selection_criteria: "accuracy_weighted"
    
  data_requirements:
    minimum_historical_periods: 12  # months
    minimum_deals_per_model: 100
    data_quality_threshold: 0.8
    
  forecast_types:
    - "revenue_projection"
    - "deal_probability"
    - "pipeline_velocity"
    - "conversion_rates"
    - "seasonal_trends"
    - "risk_assessment"

models:
  dealProbabilityModel: "gradient_boosting"
  revenueProjectionModel: "time_series_ensemble"
  churnPredictionModel: "logistic_regression"
  leadScoringIntegration: true
  
  deal_probability:
    algorithm: "gradient_boosting"
    features:
      - "deal_stage"
      - "deal_value"
      - "days_in_stage"
      - "contact_frequency"
      - "lead_score"
      - "industry"
      - "company_size"
      - "sales_rep_performance"
      - "seasonal_factors"
      - "competitor_presence"
    
    hyperparameters:
      n_estimators: 100
      learning_rate: 0.1
      max_depth: 6
      min_samples_split: 10
      validation_split: 0.2
    
    retraining:
      frequency: "weekly"
      trigger_conditions:
        - "accuracy_drop > 0.05"
        - "new_data_threshold > 1000"
        - "manual_request"
  
  revenue_projection:
    algorithm: "time_series_ensemble"
    components:
      - "arima"
      - "exponential_smoothing"
      - "neural_network"
      - "linear_regression"
    
    ensemble_weights:
      arima: 0.3
      exponential_smoothing: 0.2
      neural_network: 0.3
      linear_regression: 0.2
    
    seasonality:
      detect_automatically: true
      periods: [7, 30, 90, 365]  # days
      decomposition_method: "multiplicative"
    
    external_factors:
      - "market_conditions"
      - "economic_indicators"
      - "industry_trends"
      - "competitive_activity"

  churn_prediction:
    algorithm: "logistic_regression"
    features:
      - "engagement_score"
      - "communication_frequency"
      - "deal_velocity"
      - "competitor_mentions"
      - "contract_terms"
      - "stakeholder_changes"
      - "support_ticket_volume"
    
    risk_categories:
      high_risk: 0.8
      medium_risk: 0.5
      low_risk: 0.2

analytics:
  pipelineAnalysis: true
  seasonalityDetection: true
  trendAnalysis: true
  anomalyDetection: true
  competitiveIntelligence: true
  
  pipeline_metrics:
    - "velocity"
    - "conversion_rates"
    - "stage_duration"
    - "win_rate"
    - "average_deal_size"
    - "time_to_close"
    - "pipeline_coverage"
    - "deal_slippage"
  
  trend_detection:
    lookback_periods: [30, 60, 90, 180, 365]  # days
    statistical_tests:
      - "mann_kendall"
      - "linear_regression"
      - "seasonal_decompose"
    
    significance_level: 0.05
    trend_strength_threshold: 0.3
  
  anomaly_detection:
    methods:
      - "isolation_forest"
      - "one_class_svm"
      - "statistical_outliers"
    
    sensitivity: "medium"  # low, medium, high
    alert_threshold: 2.5  # standard deviations
    
  seasonality:
    auto_detection: true
    manual_patterns:
      quarterly: [1, 4, 7, 10]  # months with higher activity
      monthly: [15, 30]  # days of month with higher activity
      weekly: [2, 3, 4]  # Tuesday, Wednesday, Thursday
    
    adjustment_factors:
      q1: 0.9
      q2: 1.1
      q3: 0.8
      q4: 1.3

alerts:
  forecastVarianceThreshold: 0.15  # 15% variance trigger
  riskThreshold: 0.7
  opportunityThreshold: 0.8
  performanceAlerts: true
  
  alert_conditions:
    high_variance:
      threshold: 0.20
      severity: "warning"
      frequency: "daily"
    
    low_confidence:
      threshold: 0.60
      severity: "info"
      frequency: "weekly"
    
    model_drift:
      threshold: 0.10
      severity: "critical"
      frequency: "immediate"
    
    pipeline_anomaly:
      threshold: 2.0  # standard deviations
      severity: "warning"
      frequency: "immediate"
    
    deal_risk:
      probability_threshold: 0.70
      risk_factor_count: 2
      severity: "high"
      frequency: "daily"

claude_forecasting:
  model: "claude-3-5-sonnet-20241022"
  maxTokens: 3000
  temperature: 0.2
  streamResponses: false
  
  caching:
    enabled: true
    ttl: 3600  # 1 hour
  
  prompts:
    revenue_forecast: |
      Analyze this sales data and generate predictive insights:
      
      Historical Performance: {historicalData}
      Current Pipeline: {pipelineData}
      Statistical Forecast: {statisticalForecast}
      Market Context: {marketContext}
      Time Range: {timeRange}
      
      Provide insights on:
      1. Revenue projection accuracy and confidence
      2. Key factors driving forecast changes
      3. Risk factors that could impact projections
      4. Opportunities for pipeline acceleration
      5. Recommended actions for sales leadership
      
      Focus on actionable insights with specific recommendations.
      
    deal_probability: |
      Assess the probability of this deal closing successfully:
      
      Deal Information: {dealData}
      Similar Historical Deals: {similarDeals}
      Statistical Probability: {statisticalProbability}
      Market Context: {marketContext}
      
      Analyze:
      1. Factors supporting deal closure
      2. Risk factors and potential obstacles
      3. Recommended actions to increase probability
      4. Optimal timing and next steps
      5. Stakeholder engagement strategy
      
      Provide probability estimate with confidence level and reasoning.
      
    scenario_analysis: |
      Generate scenario-based forecasts:
      
      Base Forecast: {baseForecast}
      Scenario Type: {scenario}
      Risk Factors: {riskFactors}
      Opportunities: {opportunities}
      
      For {scenario} scenario, adjust the base forecast considering:
      1. Market condition impacts
      2. Competitive positioning changes
      3. Internal capability variations
      4. External economic factors
      
      Provide adjusted revenue projections with probability distributions.

statistical_modeling:
  frameworks:
    - "scikit-learn"
    - "statsmodels"
    - "tensorflow"
    - "xgboost"
  
  feature_engineering:
    automated: true
    custom_features:
      - "deal_momentum"
      - "stakeholder_engagement_score"
      - "competitive_threat_level"
      - "budget_cycle_alignment"
      - "implementation_complexity"
    
    interaction_features: true
    polynomial_features: false
    feature_selection: "recursive_elimination"
  
  model_validation:
    cross_validation: "time_series_split"
    validation_periods: 5
    test_size: 0.2
    
    metrics:
      regression: ["mae", "rmse", "mape", "r2"]
      classification: ["accuracy", "precision", "recall", "f1", "auc"]
    
    backtesting:
      enabled: true
      lookback_periods: 12
      rebalancing_frequency: "monthly"

risk_assessment:
  categories:
    - "deal_specific"
    - "competitive"
    - "market_conditions"
    - "internal_capabilities"
    - "customer_factors"
  
  risk_factors:
    deal_specific:
      - "long_sales_cycle"
      - "high_deal_value"
      - "multiple_decision_makers"
      - "complex_requirements"
      - "budget_constraints"
    
    competitive:
      - "strong_incumbent"
      - "price_competition"
      - "feature_gaps"
      - "relationship_disadvantage"
    
    market_conditions:
      - "economic_downturn"
      - "industry_consolidation"
      - "regulatory_changes"
      - "seasonal_factors"
    
    internal_capabilities:
      - "resource_constraints"
      - "skill_gaps"
      - "capacity_limitations"
      - "implementation_challenges"
    
    customer_factors:
      - "financial_stability"
      - "organizational_changes"
      - "priority_shifts"
      - "stakeholder_turnover"
  
  mitigation_strategies:
    proactive_measures:
      - "relationship_strengthening"
      - "value_demonstration"
      - "competitive_differentiation"
      - "stakeholder_mapping"
    
    reactive_measures:
      - "discount_authorization"
      - "executive_escalation"
      - "partnership_leverage"
      - "timeline_adjustment"

monitoring:
  metrics:
    - "forecast_accuracy"
    - "model_performance"
    - "prediction_confidence"
    - "data_quality"
    - "processing_time"
    - "cache_hit_rate"
    - "error_rate"
    - "alert_frequency"
  
  alerts:
    - condition: "forecast_accuracy < 0.70"
      severity: "critical"
    - condition: "model_drift > 0.10"
      severity: "warning"
    - condition: "data_quality < 0.80"
      severity: "warning"
    - condition: "processing_time > 10s"
      severity: "info"
    - condition: "error_rate > 0.05"
      severity: "critical"

logging:
  level: "info"
  includeModelDetails: true
  includePredictionData: false  # Privacy
  sensitiveFields:
    - "deal_values"
    - "customer_names"
    - "revenue_numbers"

security:
  dataRetention: "2y"  # Model training requires longer retention
  predictionRetention: "90d"
  encryption: "aes-256"
  accessControl: "rbac"
  auditLogging: true
  
  data_anonymization:
    enabled: true
    methods:
      - "pseudonymization"
      - "aggregation"
      - "noise_injection"
    
    protected_fields:
      - "customer_identifiers"
      - "sales_rep_details"
      - "specific_deal_terms"

compliance:
  model_governance:
    version_control: true
    change_tracking: true
    approval_process: true
    documentation_required: true
  
  explainability:
    feature_importance: true
    prediction_explanations: true
    model_interpretability: "required"
    
  bias_detection:
    enabled: true
    protected_attributes:
      - "customer_size"
      - "industry"
      - "geographic_region"
    
    fairness_metrics:
      - "demographic_parity"
      - "equalized_odds"
      - "calibration"

performance:
  caching:
    model_cache_size: "500MB"
    prediction_cache_ttl: 1800  # 30 minutes
    feature_cache_ttl: 3600     # 1 hour
  
  optimization:
    model_compression: true
    prediction_batching: true
    parallel_processing: true
    gpu_acceleration: false
    
  scalability:
    horizontal_scaling: true
    load_balancing: "round_robin"
    auto_scaling_threshold: 0.80
    max_instances: 10