# Kubernetes Secrets for Sales AI Agent Platform
# NOTE: In production, use Sealed Secrets, External Secrets Operator, or similar for secure secret management

apiVersion: v1
kind: Secret
metadata:
  name: sales-ai-secrets
  namespace: sales-ai-agent
  labels:
    app.kubernetes.io/name: sales-ai-agent
    app.kubernetes.io/component: secrets
type: Opaque
data:
  # Database credentials (base64 encoded)
  # POSTGRES_PASSWORD: c2VjdXJlX3Bhc3N3b3JkXzEyMw== (secure_password_123)
  POSTGRES_PASSWORD: c2VjdXJlX3Bhc3N3b3JkXzEyMw==
  
  # Redis password (base64 encoded)
  # REDIS_PASSWORD: cmVkaXNfcGFzc3dvcmRfMTIz (redis_password_123)
  REDIS_PASSWORD: cmVkaXNfcGFzc3dvcmRfMTIz
  
  # JWT Secret (base64 encoded)
  # JWT_SECRET: and2dGpfajMzXzUzY3IzNF9zYWxlc19haV9hZ2VudA== (jwt_j33_53cr34_sales_ai_agent)
  JWT_SECRET: and2dGpfajMzXzUzY3IzNF9zYWxlc19haV9hZ2VudA==
  
  # Encryption key (base64 encoded)
  # ENCRYPTION_KEY: ZW5jcnlwdGlvbl9rZXlfNjRfYml0X2hleFN0cmluZ0ZvclNhbGVzQUk= (encryption_key_64_bit_hexStringForSalesAI)
  ENCRYPTION_KEY: ZW5jcnlwdGlvbl9rZXlfNjRfYml0X2hleFN0cmluZ0ZvclNhbGVzQUk=
  
  # External API Keys (replace with actual keys)
  # ANTHROPIC_API_KEY: <base64-encoded-anthropic-api-key>
  ANTHROPIC_API_KEY: YW50aHJvcGljX2FwaV9rZXlfcGxhY2Vob2xkZXI=
  
  # SENDGRID_API_KEY: <base64-encoded-sendgrid-api-key>
  SENDGRID_API_KEY: c2VuZGdyaWRfYXBpX2tleV9wbGFjZWhvbGRlcg==
  
  # DEEPGRAM_API_KEY: <base64-encoded-deepgram-api-key>
  DEEPGRAM_API_KEY: ZGVlcGdyYW1fYXBpX2tleV9wbGFjZWhvbGRlcg==
  
  # CLEARBIT_API_KEY: <base64-encoded-clearbit-api-key>
  CLEARBIT_API_KEY: Y2xlYXJiaXRfYXBpX2tleV9wbGFjZWhvbGRlcg==

---
apiVersion: v1
kind: Secret
metadata:
  name: monitoring-secrets
  namespace: sales-ai-agent
  labels:
    app.kubernetes.io/name: monitoring
    app.kubernetes.io/component: secrets
type: Opaque
data:
  # Grafana admin password (base64 encoded)
  # GRAFANA_PASSWORD: Z3JhZmFuYV9hZG1pbl8xMjM= (grafana_admin_123)
  GRAFANA_PASSWORD: Z3JhZmFuYV9hZG1pbl8xMjM=

---
apiVersion: v1
kind: Secret
metadata:
  name: tls-secret
  namespace: sales-ai-agent
  labels:
    app.kubernetes.io/name: sales-ai-agent
    app.kubernetes.io/component: tls
type: kubernetes.io/tls
data:
  # TLS certificate and key (base64 encoded)
  # Replace with actual certificate and key
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0t...
  tls.key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0t...